### ISSUE TITLE
Toram Online sources?

### ISSUE THREAD

**Issue by Thomas-Malh** [toramtools/toramtools.github.io#2]
Hi, great tools!
I was wondering, could you add the sources for the main quests experience points? (api or something)
Or is it your own sources?

**Comment by toramtools** [comment]
Hello thomas, main quest experience values are [stored directly on code](https://github.com/toramtools/toramtools.github.io/blob/master/js/xp.js) and updated manually through time. This way it won't require me to pay to host an API or database.

Best regards.
